import { countryDetail, galleryGroupProps } from "./types";

export const steps = ["Confirm information", "Payments", "Complete"];

export const country_list = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const visaRegex = /^4[0-9]{12}(?:[0-9]{3})?$/;

export const cvvCodeRegex = /^[0-9]{3,4}$/;

export const courouselData: countryDetail[] = [
  {
      country: 'Chile',
      destination: 'Torres del Paine National Park',
      source: 'Carousel/csujhbh4tnrpk4x4zwa9'
  },
  {
      country: 'Croatia',
      destination: 'Plitvice Lakes National Park',
      source: 'Carousel/xypvtfthd0it63de18xr'
  },
  {
      country: 'New Zealand',
      destination: 'Lake Tekapo',
      source: 'Carousel/x7shbpwiqgsenft9qkbl'
  },
  {
      country: 'Japan',
      destination: 'Fuji Mount',
      source: 'Carousel/misg8ecxyy4nziyspoc1'
  },
  {
      country: 'Viet Nam',
      destination: 'Ha Long Bay',
      source: 'Carousel/r0v3owiletideu0lurcn'
  },
]

export const hotelDescription = [
  'Epitomize excellence in service, providing a meticulously curated and luxurious experience for guests.',
  'Defined by exceptional attention to detail, personalized care, and an unwavering commitment to exceeding customer expectations',
  "Ensures that customers receive the most competitive prices available, backed by a commitment to match or beat any competitor's offer."
]

export const defaultMetaProps = {
  title: "Xplore",
  description: "Xplore is your ultimate travel guide for discovering new destinations and planning your next adventure.",
  robots: 'all'
}

export const emailRegex = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/;

export const passwordRegex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;

export const nameRegex = /^[a-zA-Z]{4,30}(?: [a-zA-Z]+){0,5}$/;

export const galleryGroupImg: galleryGroupProps[] = [
  {
    imgSrc: "Background/nlqfojwt9wbh0yuw5yzk",
    region: "Asia",
  },
  {
    imgSrc: "Background/fx6i7rnmq7mkzpmgxfzr",
    region: "Africa",
  },
  {
    imgSrc: "Background/wczkt2urytrrgkjgbcqx",
    region: "Europe",
  },
  {
    imgSrc: "Background/szidyar7fphtisskl7ci",
    region: "Americas",
  },
];